### PR TITLE
Upgrade to fs-capacitor v4

### PR DESCRIPTION
**Pull request by mike-marcacci**
I've done a rework of fs-capacitor to support node 13. This involved using the `readable-stream` package instead of node's stream library in order to simply continued compatibility with node v8.x, which we can drop at the end of 2019.

I spent the better part of a day trying to figure out exporting interoperable es6 and commonjs modules now that I have a commonjs dependency, and I finally just gave up. Without any useful guidance or pathway put forward by node for interoperability, the only choice here is to chose a single module system, which will be commonjs for the immediate future.

@jaydenseric I'll bet you have some thoughts on this matter, which I'd love to hear.

I've also [opened an issue](https://github.com/mike-marcacci/fs-capacitor/issues/17) in `fs-capacitor` to track how to maintain support for es modules.

Regardless, this is updated to work with the newest `fs-capacitor` and adds compatibility with node v13.

### CODE REVIEW

**Comment by mike-marcacci** [comment]
Preparing and testing only js files succeeds an node 8, 10, and 13:

```bash
if [ -d 'lib' ]; then rm -rf lib; fi; npx babel src -d lib && npx tap --test-ignore=src --100
```

**Comment by mike-marcacci** [comment]
OK, I've worked around all the quirks here and have everything passing on all target versions in docker. It appears that there is a flaw in a newly released dependency of eslint which is causing these failures on CI but is unrelated.

**Comment by mike-marcacci** [comment]
I saw you just published a new major version of `eslint-config-env` yesterday, which fixes the issue that was crashing running eslint.

Additionally, [this commit in eslint](https://github.com/eslint/eslint/commit/2d6e345e3c2626b0f2252f22cfaffdf53ea0871a) no longer works on node `v8.5.x` but _does_ work on the latest version of node `v8.x`. I updated the engine and CI settings accordingly. I'm excited to entirely drop support for node v8 in December...

**Comment by mike-marcacci** [comment]
OK, I added the change log.

It appears that the tap/nyc combo are not respecting the `.nycrc.json` file, so I had to add the flag `--nyc-arg=--exclude='**/test-helpers/**'` (which is now redundant with the file). I haven't had a chance to dive into this.

Technically the engine bump from node 8.5 to node 8.10 is a breaking change. If you are instead interested in cutting a new major that adds support for node 13 but drops support for node 8 (essentially a month and a half before its LTS end of life), I've already published `fs-capacitor` v5, which does exactly that.

Because there are not big feature changes or fixes here, we could simply continue to "support" graphql-upload version 8.x through the end of the year (and expect other tools like Apollo to continue using it for that timeline), while publishing version 9 with support for node 10 through 13.

**Comment by jaydenseric** [comment]
Regarding: https://github.com/jaydenseric/graphql-upload/pull/166/commits/14afd0752b6b94f6cf56bea3f79b74f6f9201830

Removing `.nycrc.json` was deliberate in https://github.com/jaydenseric/graphql-upload/pull/166/commits/0f92002a66a6a3088d2b40ffa23fc56ccc5306c2; `tap` now automatically ignores test files, and since the `test-helpers` directory was not being ignored anyway due to a tap bug, there is no purpose to keeping the file anymore.

**Comment by jaydenseric** [comment]
Awesome 🙌

**Pull request merged**
