### PR TITLE
Error on unreplaced Upload scalar

### LINKED ISSUE #175: Should throw error when a JSON instead of a File is received from client
When I send a JSON (number, string, object, etc) instead of a File from client, I don't get any errors and the argument returns a JS Object instead of [Promise\<FileUpload\>](https://github.com/jaydenseric/graphql-upload#type-fileupload).  
Is this working correctly? Shouldn't this throw an error in the `parseValue` of scalar? We are expecting a stream after all.  
This forces us to validate the input every time we are using `Upload` scalar.  

I'm using Apollo Server (and `apollo-upload-client` which does not matter in this scenario)

### PR DESCRIPTION
**Pull request by mike-marcacci**
This fixes #175.

### CODE REVIEW

**Comment by mike-marcacci** [comment]
It looks like more coverage is being requested, since the scalar file was previously untested (and now it's partially tested).

I won't have a chance to add the other tests today, but figured I'd get this PR in nonetheless.

**Comment by jaydenseric** [comment]
Great work for looking into this so quickly! I'm not sure when I'll be able to give it a detailed review, but just a quick thought: Should we use a `TypeError`? Graphql.js is using it now, see https://github.com/graphql/graphql-js/pull/1827.

**Comment by mike-marcacci** [comment]
I don't know how you can stay so up to date on all these things! I would have avoided using a `TypeError` on my own (since I most typically associate it with the wrong JS type being passed to a function) but I see that the ecosystem is using it here so I agree we should follow suit.

**Comment by jaydenseric** [comment]
Wouldn't this approach incorrectly error when the scalar is used correctly?

**Comment by jaydenseric** [comment]
I'm working on an alternative, really nice but more complicated solution.

**Pull request closed without merging**
