### PR TITLE
build(deps): dump object-path from 0.11.4 to 0.11.5

### PR DESCRIPTION
**Pull request by damingerdai**
# Summary
There is a prototype pollution for object-path, please upgrade to version >= 0.11.5.

# Changelog
build(deps): dump object-path from 0.11.4 to 0.11.5

#  More info 
[More info](https://www.npmjs.com/advisories/1573)

### CODE REVIEW

**Comment by jaydenseric** [comment]
Note that because the `object-path` dependency was already declared as `^0.11.4` so npm will install the latest 0.11.x patch version (currently v0.11.5). So `graphql-upload` is not currently causing the vulnerable `0.11.4` version to be installed and the change in this PR to `^0.11.5` is technically unnecessary.

**Comment by citypaul** [comment]
@jaydenseric I've created an issue for this in Apollo Server as this issue has started causing our CI runs to fail: https://github.com/apollographql/apollo-server/issues/4672

I think the reason this does cause failures in dependent libraries will be due to the way yarn.lock works. So it's probably worth updating this package.json ultimately.

**Comment by jaydenseric** [comment]
@citypaul as explained [here](https://github.com/apollographql/apollo-server/issues/4672#issuecomment-712832455):

A lockfile in your project purposefully freezes the dependency graph in place. It wouldn't solve your problem if I published the change in this PR in a patch release because like how your project's lockfile has frozen the `object-path` version in place, the `graphql-upload` version would also been frozen. You would only get the current patch releases for either package in `node_modules` by deleting the lockfile and `node_modules`, and doing a fresh npm/Yarn install.

**Comment by citypaul** [comment]
Thanks @jaydenseric, this is working for us now after taking your advice. Useful, cheers!

**Comment by damingerdai** [comment]
i agree with @jaydenseric. i will close this pr.

**Comment by tal130** [comment]
when this is plan to release?

**Comment by jaydenseric** [comment]
@tal130 please read my earlier comments in this issue.

**Pull request closed without merging**
